/**
 * Multi-language synonym dictionary for Excel header → DB field matching.
 *
 * Each DB field maps to an array of possible header synonyms
 * in English, French and Arabic.  All values are stored in lower-case
 * and diacritics-stripped so they can be compared with normalised headers.
 */

export type SynonymDictionary = Record<string, string[]>;

// ──────────────────────────────────────────────
// STAFF
// ──────────────────────────────────────────────
export const STAFF_SYNONYMS: SynonymDictionary = {
  fullName: [
    'full name',
    'fullname',
    'name',
    'staff name',
    'employee name',
    'nom complet',
    'nom',
    'prenom et nom',
    'nom et prenom',
    'الاسم الكامل',
    'الاسم',
    'اسم الموظف',
  ],
  email: [
    'email',
    'e-mail',
    'email address',
    'mail',
    'adresse email',
    'courriel',
    'adresse e-mail',
    'البريد الالكتروني',
    'الايميل',
    'بريد الكتروني',
  ],
  phone: [
    'phone',
    'phone number',
    'tel',
    'telephone',
    'mobile',
    'cell',
    'telephone',
    'numero de telephone',
    'tel',
    'portable',
    'رقم الهاتف',
    'الهاتف',
    'الجوال',
    'موبايل',
  ],
  role: [
    'role',
    'position',
    'job title',
    'title',
    'type',
    'role',
    'poste',
    'fonction',
    'titre',
    'الدور',
    'المنصب',
    'الوظيفة',
  ],
  password: ['password', 'pass', 'mot de passe', 'كلمة المرور', 'كلمة السر'],
};

// ──────────────────────────────────────────────
// FAMILIES
// ──────────────────────────────────────────────
export const FAMILY_SYNONYMS: SynonymDictionary = {
  fullName: [
    'full name',
    'fullname',
    'name',
    'parent name',
    'family name',
    'nom complet',
    'nom',
    'nom du parent',
    'prenom et nom',
    'الاسم الكامل',
    'الاسم',
    'اسم الوالد',
    'اسم العائلة',
  ],
  email: [
    'email',
    'e-mail',
    'email address',
    'mail',
    'parent email',
    'adresse email',
    'courriel',
    'adresse e-mail',
    'email du parent',
    'البريد الالكتروني',
    'الايميل',
    'بريد الكتروني',
  ],
  phone: [
    'phone',
    'phone number',
    'tel',
    'telephone',
    'mobile',
    'cell',
    'telephone',
    'numero de telephone',
    'tel',
    'portable',
    'رقم الهاتف',
    'الهاتف',
    'الجوال',
  ],
  password: ['password', 'pass', 'mot de passe', 'كلمة المرور', 'كلمة السر'],
};

// ──────────────────────────────────────────────
// CHILDREN
// ──────────────────────────────────────────────
export const CHILDREN_SYNONYMS: SynonymDictionary = {
  fullName: [
    'full name',
    'fullname',
    'name',
    'child name',
    "child's name",
    'nom complet',
    'nom',
    "nom de l'enfant",
    'prenom',
    'الاسم الكامل',
    'الاسم',
    'اسم الطفل',
  ],
  dateOfBirth: [
    'date of birth',
    'dob',
    'birth date',
    'birthday',
    'date de naissance',
    'naissance',
    'تاريخ الميلاد',
    'تاريخ الولادة',
  ],
  gender: ['gender', 'sex', 'genre', 'sexe', 'الجنس'],
  diagnosis: [
    'diagnosis',
    'condition',
    'medical condition',
    'diagnostic',
    'condition medicale',
    'التشخيص',
    'الحالة الطبية',
  ],
  medicalHistory: [
    'medical history',
    'history',
    'antecedents medicaux',
    'historique medical',
    'التاريخ الطبي',
    'السوابق الطبية',
  ],
  allergies: ['allergies', 'allergy', 'allergies', 'الحساسية'],
  medications: [
    'medications',
    'medication',
    'meds',
    'drugs',
    'medicaments',
    'traitement',
    'الادوية',
    'العلاج',
  ],
  notes: [
    'notes',
    'comments',
    'remarks',
    'additional notes',
    'notes',
    'remarques',
    'commentaires',
    'ملاحظات',
    'تعليقات',
  ],
  parentEmail: [
    'parent email',
    "parent's email",
    'family email',
    'guardian email',
    'email du parent',
    'courriel du parent',
    'بريد الوالد',
    'ايميل الوالد',
    'بريد ولي الامر',
  ],
};

// ──────────────────────────────────────────────
// FAMILIES + CHILDREN (combined sheet)
// ──────────────────────────────────────────────
export const FAMILY_CHILDREN_SYNONYMS: SynonymDictionary = {
  // Parent fields
  parentName: [
    'parent name',
    'family name',
    'parent full name',
    'guardian name',
    'nom du parent',
    'nom de famille',
    'nom complet du parent',
    'اسم الوالد',
    'اسم ولي الامر',
    'اسم العائلة',
  ],
  parentEmail: [
    'parent email',
    "parent's email",
    'family email',
    'guardian email',
    'email',
    'email du parent',
    'courriel du parent',
    'adresse email',
    'بريد الوالد',
    'ايميل الوالد',
    'بريد ولي الامر',
    'البريد الالكتروني',
  ],
  parentPhone: [
    'parent phone',
    "parent's phone",
    'family phone',
    'phone',
    'telephone du parent',
    'tel du parent',
    'telephone',
    'هاتف الوالد',
    'رقم هاتف الوالد',
    'رقم الهاتف',
  ],
  parentPassword: [
    'parent password',
    'password',
    'pass',
    'mot de passe',
    'mot de passe du parent',
    'كلمة مرور الوالد',
    'كلمة المرور',
  ],
  // Child fields
  childName: [
    'child name',
    "child's name",
    'child full name',
    'name of child',
    "nom de l'enfant",
    "prenom de l'enfant",
    "nom complet de l'enfant",
    'اسم الطفل',
    'الاسم الكامل للطفل',
  ],
  dateOfBirth: [
    'date of birth',
    'dob',
    'birth date',
    'child dob',
    'date de naissance',
    "date de naissance de l'enfant",
    'تاريخ الميلاد',
    'تاريخ ميلاد الطفل',
  ],
  gender: [
    'gender',
    'sex',
    'child gender',
    'genre',
    'sexe',
    "sexe de l'enfant",
    'الجنس',
    'جنس الطفل',
  ],
  diagnosis: ['diagnosis', 'condition', 'diagnostic', 'التشخيص'],
  medicalHistory: [
    'medical history',
    'history',
    'antecedents medicaux',
    'التاريخ الطبي',
  ],
  allergies: ['allergies', 'allergy', 'allergies', 'الحساسية'],
  medications: ['medications', 'medication', 'medicaments', 'الادوية'],
  notes: ['notes', 'comments', 'remarks', 'notes', 'remarques', 'ملاحظات'],
};
